name: Release (Docker)

on:
  push:
    tags:
      - 'v*'

jobs:
  release-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Setup | Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            illustar0/gtm-proxy
            ghcr.io/illustar0/gtm-proxy
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest
          labels: |
            org.opencontainers.image.authors=${{vars.GH_EMAIL}}

      - name: Setup | Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup | Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Setup | Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup | Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish | Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          platforms: ${{ matrix.platform }}
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
