name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
          token: ${{ secrets.GH_PAT }}
          persist-credentials: false


      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup | Set up Python
        run: uv python install

      - name: Release | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          changelog: true
          github_token: ${{ secrets.GH_PAT }}
          git_committer_name: ${{vars.GH_USERNAME}}
          git_committer_email: ${{vars.GH_EMAIL}}